/**
 * Outreach engine — triggered when a driver applies to an unclaimed AGGREGATED job.
 *
 * Behaviour:
 *  - Creates or retrieves the EmployerClaim for the job's organizationNumber.
 *  - Respects throttle: max one outreach per org per OUTREACH_THROTTLE_DAYS (default 7).
 *  - Review mode (default): logs the draft email to console + AdminAuditLog instead of
 *    sending. Flip OUTREACH_AUTO_SEND=true to send automatically once calibrated.
 *  - Opt-out: if EmployerClaim.optedOutAt is set, no outreach is sent.
 */

import { prisma } from "./prisma.js";
import { sendEmail } from "./email.js";

// ─── Config ───────────────────────────────────────────────────────────────────

const THROTTLE_DAYS = parseInt(process.env.OUTREACH_THROTTLE_DAYS ?? "7", 10);
const AUTO_SEND     = process.env.OUTREACH_AUTO_SEND === "true";
const BASE_URL      = process.env.FRONTEND_URL || "https://transportplattformen.se";
const FROM_NAME     = process.env.EMAIL_FROM_NAME || "Sveriges Transportplattform";

// ─── Claim helpers ────────────────────────────────────────────────────────────

/**
 * Returns the EmployerClaim for an organizationNumber, creating it if needed.
 * claimToken is auto-generated by the @default(cuid()) on the model.
 */
export async function getOrCreateClaim(organizationNumber) {
  return prisma.employerClaim.upsert({
    where:  { organizationNumber },
    create: { organizationNumber },
    update: {}, // no-op if exists
  });
}

/**
 * Mark a claim as opted out. Future calls to triggerOutreach will be no-ops.
 */
export async function optOutClaim(token) {
  const claim = await prisma.employerClaim.findUnique({ where: { claimToken: token } });
  if (!claim) return null;
  if (claim.optedOutAt) return claim; // already opted out
  return prisma.employerClaim.update({
    where: { claimToken: token },
    data: { optedOutAt: new Date() },
  });
}

// ─── Main trigger ─────────────────────────────────────────────────────────────

/**
 * Triggered after a driver submits an Application to an unclaimed AGGREGATED job.
 *
 * @param {object} job          — full Job record (must include organizationNumber, applyEmail, employerEmail, company, title, id, sourceUrl)
 * @param {number} applicationCount — total number of applications for this org so far
 */
export async function triggerOutreach(job, applicationCount) {
  if (!job.organizationNumber) {
    console.log("[Outreach] Jobb saknar organizationNumber — hoppar över");
    return { skipped: true, reason: "no_org_number" };
  }

  const claim = await getOrCreateClaim(job.organizationNumber);

  if (claim.optedOutAt) {
    console.log(`[Outreach] ${job.organizationNumber} har avregistrerat sig — hoppar över`);
    return { skipped: true, reason: "opted_out" };
  }

  // Throttle: max one outreach per org per THROTTLE_DAYS
  if (claim.outreachSentAt) {
    const daysSince = (Date.now() - new Date(claim.outreachSentAt).getTime()) / 864e5;
    if (daysSince < THROTTLE_DAYS) {
      console.log(`[Outreach] ${job.organizationNumber} fick utskick för ${daysSince.toFixed(1)} dgr sedan — hoppar över (throttle: ${THROTTLE_DAYS} dgr)`);
      // Update count so the next email mentions the total
      await prisma.employerClaim.update({
        where: { id: claim.id },
        data: { outreachCount: { increment: 1 } },
      });
      return { skipped: true, reason: "throttled" };
    }
  }

  // Best available contact
  const contactEmail = job.applyEmail || job.employerEmail || null;
  const claimUrl = `${BASE_URL}/anslut/${claim.claimToken}`;
  const optOutUrl = `${BASE_URL}/avregistrera/${claim.claimToken}`;

  const subjectLine = `${applicationCount > 1 ? `${applicationCount} förare har sökt` : "En förare har sökt"} er annons på STP`;

  const bodyText = [
    `Hej ${job.company},`,
    "",
    `${applicationCount > 1 ? `${applicationCount} kvalificerade lastbilsförare har` : "En kvalificerad lastbilsförare har"} sökt er tjänst "${job.title}" via Sveriges Transportplattform (STP).`,
    "",
    "För att se kandidaterna och ta över er annons på STP, klicka på länken nedan:",
    "",
    claimUrl,
    "",
    "Det är gratis att se ansökningarna och skapa ett konto. Ni bestämmer sedan om ni vill bli aktiva på plattformen.",
    "",
    "──",
    `STP hittade er annons på Arbetsförmedlingen och publicerade den för att nå rätt förare. Ni kan alltid se originalannonsen här: ${job.sourceUrl || "arbetsformedlingen.se"}`,
    "",
    `Vill ni inte ta emot fler sådana meddelanden? Klicka här för att avregistrera er: ${optOutUrl}`,
    "",
    `Med vänliga hälsningar,`,
    FROM_NAME,
  ].join("\n");

  if (AUTO_SEND && contactEmail) {
    try {
      await sendEmail({
        to: contactEmail,
        subject: subjectLine,
        text: bodyText,
        ctaUrl: claimUrl,
        ctaText: "Se kandidaterna →",
      });
      console.log(`[Outreach] Skickade till ${contactEmail} för org ${job.organizationNumber}`);
    } catch (err) {
      console.error(`[Outreach] Misslyckades skicka till ${contactEmail}:`, err.message);
      return { skipped: false, sent: false, error: err.message, claimToken: claim.claimToken };
    }
  } else {
    // Review mode — log to console so Oliver can inspect before enabling auto-send
    console.log("─────────────────────────────────────────────────────────");
    console.log("[Outreach REVIEW MODE] Skulle skicka e-post:");
    console.log(`  Till:     ${contactEmail || "(ingen e-post tillgänglig)"}`);
    console.log(`  Ämne:     ${subjectLine}`);
    console.log(`  Claim-URL: ${claimUrl}`);
    console.log(`  Org.nr:   ${job.organizationNumber}`);
    console.log(`  Jobb:     ${job.title} @ ${job.company}`);
    console.log(`  Ansök.nr: ${applicationCount}`);
    if (!contactEmail) {
      console.log("  OBS: Ingen kontakte-post hittad — inget skulle skickas ens i auto-läge");
    }
    console.log("─────────────────────────────────────────────────────────");
  }

  // Update claim state
  await prisma.employerClaim.update({
    where: { id: claim.id },
    data: {
      outreachSentAt: new Date(),
      outreachCount:  { increment: 1 },
    },
  });

  // Log to AdminAuditLog for review queue visibility
  try {
    const systemUser = await prisma.user.findFirst({
      where: { email: process.env.AGGREGATED_JOBS_USER_EMAIL || "system-aggregated@stp.internal" },
      select: { id: true },
    });
    if (systemUser) {
      await prisma.adminAuditLog.create({
        data: {
          adminUserId:  systemUser.id,
          adminEmail:   "system-aggregated@stp.internal",
          action:       "OUTREACH_QUEUED",
          targetType:   "EmployerClaim",
          metadata: {
            organizationNumber: job.organizationNumber,
            company:            job.company,
            jobTitle:           job.title,
            contactEmail:       contactEmail ?? null,
            claimToken:         claim.claimToken,
            autoSent:           AUTO_SEND && !!contactEmail,
            applicationCount,
          },
        },
      });
    }
  } catch { /* non-critical */ }

  return {
    skipped: false,
    sent: AUTO_SEND && !!contactEmail,
    reviewMode: !AUTO_SEND,
    claimToken: claim.claimToken,
    contactEmail: contactEmail ?? null,
  };
}
