/**
 * Sveriges största städer med trucking-relevans.
 * Varje stad mappas till sin region (för jobbhämtning) och har
 * unik SEO-text om transportlandskapet i just den staden.
 *
 * URL-mönster: /ce-jobb/[slug]
 */
export const cityPages = [
  {
    slug: "stockholm",
    name: "Stockholm",
    region: "Stockholm",
    regionSlug: "stockholm",
    tagline: "Nordens största logistiknav",
    desc: "CE-jobb och lastbilsjobb i Stockholm — Sveriges största arbetsmarknad för yrkesförare.",
    transport: "Stockholm är landets tätaste distributionsmarknad. E4, E18 och E20 möts här — och citylogistiken växer snabbt med nya terminaler i Rosersberg, Jordbro och Kungens kurva. Stark efterfrågan på CE-förare dygnet runt, framför allt natt och tidig morgon.",
    highlights: ["Stor citylogistik och last mile", "Nattdistribution i innerstad", "E4/E18/E20-korridorer", "Rosersberg och Arlanda-logistik"],
  },
  {
    slug: "goteborg",
    name: "Göteborg",
    region: "Västra Götaland",
    regionSlug: "vastra-gotaland",
    tagline: "Sveriges största hamn",
    desc: "CE-jobb och lastbilsjobb i Göteborg — hamntransport, fjärrkörning och distribution i Västsverige.",
    transport: "Göteborgs hamn är Nordens största och genererar tusentals lastbilsrörelser varje dag. Hamnlogistik, container­transport och sjötransportkoppling ger konstant behov av CE-förare. E6 och E20 är ryggraden mot resten av Sverige och Europa.",
    highlights: ["Göteborgs hamn — Nordens största", "Container och roro-transport", "E6 söderut mot Malmö/Europa", "Stora lagerkluster i Arendal och Hisingen"],
  },
  {
    slug: "malmo",
    name: "Malmö",
    region: "Skåne",
    regionSlug: "skane",
    tagline: "Porten mot Europa",
    desc: "CE-jobb och lastbilsjobb i Malmö — Öresundsbron, färjelinjer och Skandinaviens europaport.",
    transport: "Malmö är Sveriges sydligaste logistikpunkt och Skandinaviens direkta länk till Europa. Öresundsbron, färjelinjer till Polen och Tyskland, och E6/E20-korridoren gör att CE-förare med internationell erfarenhet är extra efterfrågade.",
    highlights: ["Öresundsbron och Europa-trafik", "Färjelinjer mot Polen och Tyskland", "Stor kyllogistik (lantbruk/livsmedel)", "E6/E22 mot hela Sverige"],
  },
  {
    slug: "linkoping",
    name: "Linköping",
    region: "Östergötland",
    regionSlug: "ostergotland",
    tagline: "Östergötlands logistikcentrum",
    desc: "CE-jobb och lastbilsjobb i Linköping — industritransport, fjärrkörning och distribution i Östergötland.",
    transport: "Linköping kombinerar tung industri (Saab, BAE Systems) med ett starkt logistikläge vid E4:ans sträckning mitt i Sverige. Kort avstånd till Norrköpings hamn och direktförbindelser norrut och söderut.",
    highlights: ["E4 — riksväg mitt i Sverige", "Industritransport (Saab m.fl.)", "Norrköpings hamn 30 km bort", "Distribution i Östergötland"],
  },
  {
    slug: "norrkoping",
    name: "Norrköping",
    region: "Östergötland",
    regionSlug: "ostergotland",
    tagline: "Hamnstad med E4-läge",
    desc: "CE-jobb och lastbilsjobb i Norrköping — hamnlogistik, E4 och industritransport.",
    transport: "Norrköping har en aktiv handelshamn och ett strategiskt E4-läge som gör det till ett naturligt nav för fjärrkörning och distribution i regionen. Papper­industri och livsmedelstransport dominerar godsslagen.",
    highlights: ["Norrköpings handelshamn", "E4 — rakt norrut och söderut", "Pappers- och livsmedelstransport", "Distribution i Östergötland"],
  },
  {
    slug: "jonkoping",
    name: "Jönköping",
    region: "Jönköping",
    regionSlug: "jonkoping",
    tagline: "Sveriges logistikhjärta",
    desc: "CE-jobb och lastbilsjobb i Jönköping — A6-området, e-handel och rikstransporter mitt i Sverige.",
    transport: "Jönköping kallas ofta Sveriges logistikhuvudstad. A6-området är ett av landets tätaste lagerkluster med stora e-handels­aktörer och rikstäckande distributionscentraler. Stadens geografiska mittpunkt gör den till navet för natt­transport och fjärrkörning.",
    highlights: ["A6-området — ett av Sveriges största lagerkluster", "E4 — pulsådern norrut/söderut", "E-handel och riksdistribution", "Natt­transport och fjärrkörning"],
  },
  {
    slug: "helsingborg",
    name: "Helsingborg",
    region: "Skåne",
    regionSlug: "skane",
    tagline: "Öresundsregionens norra pol",
    desc: "CE-jobb och lastbilsjobb i Helsingborg — färjetrafik till Danmark, E4 och Skånes norra logistik.",
    transport: "Helsingborg–Helsingör är Europas mest trafikerade färjeförbindelse. Utöver färjetrafiken är Helsingborg ett viktigt logistiknav längs E4 och hemort för stora distributions­centraler. Kylkedjan (frukt, grönt) är särskilt stark här.",
    highlights: ["Helsingborg–Helsingör: Europas tätaste färjelinje", "E4 längs Öresundskusten", "Kyllogistik och livsmedel", "Port of Helsingborg — aktiv handelshamn"],
  },
  {
    slug: "vasteras",
    name: "Västerås",
    region: "Västmanland",
    regionSlug: "vastmanland",
    tagline: "Mälardalen industristad",
    desc: "CE-jobb och lastbilsjobb i Västerås — industritransport, E18 och Mälardalens logistik.",
    transport: "Västerås är Mälardalens industricentrum med ABB och Hitachi Rail som dominerande arbetsgivare. E18 ger snabb koppling mot Stockholm och Oslo. Västerås hamn används för sjötransport av tunggods och råvaror längs Mälaren.",
    highlights: ["ABB och tung industritransport", "E18 Stockholm–Oslo", "Västerås hamn och Mälarsjöfart", "Distribution i Mälardalen"],
  },
  {
    slug: "orebro",
    name: "Örebro",
    region: "Örebro",
    regionSlug: "orebro",
    tagline: "Sveriges geografiska mittpunkt",
    desc: "CE-jobb och lastbilsjobb i Örebro — E18/E20-korsningen, rikstransporter och mellansveriges logistik.",
    transport: "Örebro ligger exakt där E18 och E20 möts — mitt i Sverige. Det gör staden till en naturlig omstignings­punkt för nationell distribution. Stora lager­etableringar de senaste åren har ökat efterfrågan på CE-förare markant.",
    highlights: ["E18 × E20 — rikskorsning", "Rikstäckande distributionscentraler", "Geografisk mittpunkt för Sverige", "Ökande lageretableringar"],
  },
  {
    slug: "uppsala",
    name: "Uppsala",
    region: "Uppsala",
    regionSlug: "uppsala",
    tagline: "Norra Stockholmsregionen",
    desc: "CE-jobb och lastbilsjobb i Uppsala — E4-korridor, Arlanda-logistik och norr om Stockholm.",
    transport: "Uppsala drar nytta av närheten till Stockholm och Arlanda. E4:an norrut passerar direkt, och logistik­etableringarna i Uppsalaregionen växer snabbt. Läkemedelstransporter (AstraZeneca, Pfizer) och kylkedja är starka segment.",
    highlights: ["E4 mot Stockholm och norrut", "Arlanda Airport cargo", "Läkemedel och specialtransport", "Snabbväxande lagermarknad"],
  },
  {
    slug: "sundsvall",
    name: "Sundsvall",
    region: "Västernorrland",
    regionSlug: "vasternorrland",
    tagline: "Norra Sveriges logistikport",
    desc: "CE-jobb och lastbilsjobb i Sundsvall — skogstransport, E4 norrut och Norrlands distributionshubb.",
    transport: "Sundsvall är Norrlands naturliga logistikcentrum. Skogsindustrin dominerar — timmer, papper och massa transporteras dagligen på E4:an norrut och söderut. Sundsvalls hamn hanterar bulk och industrigods.",
    highlights: ["Skogstransport och timmer", "E4 — Norrlandskusten", "Sundsvalls hamn", "Distribution i Norrland"],
  },
  {
    slug: "umea",
    name: "Umeå",
    region: "Västerbotten",
    regionSlug: "vasterbotten",
    tagline: "Norra Norrlands nav",
    desc: "CE-jobb och lastbilsjobb i Umeå — skogstransport, regional distribution och Norra Norrlands centrum.",
    transport: "Umeå är det administrativa och logistiska centrumet för norra Norrland. Skogsindustrins transporter, regional matdistribution och fjärrkörning längs E4/E12 ger stabil efterfrågan på CE-förare.",
    highlights: ["Skogsindustri och råvarutransport", "E4 och E12 västerut", "Regional distribution Västerbotten", "Umeå hamn"],
  },
  {
    slug: "lulea",
    name: "Luleå",
    region: "Norrbotten",
    regionSlug: "norrbotten",
    tagline: "Stålstaden i norr",
    desc: "CE-jobb och lastbilsjobb i Luleå — SSAB, gruvtransport och Norrbottens logistik.",
    transport: "Luleå präglas av tung industri — SSAB:s stålverk och Norrbottens gruvor skapar konstant efterfrågan på CE-förare med erfarenhet av tungt gods och specialtransport. Luleå hamn är en av Sveriges viktigaste i norr.",
    highlights: ["SSAB och stålverk — tung transport", "Gruvtransporter (LKAB-korridor)", "Luleå hamn och isbrytarlogistik", "E4 — Norrlandskusten"],
  },
  {
    slug: "gavle",
    name: "Gävle",
    region: "Gävleborg",
    regionSlug: "gavleborg",
    tagline: "Norrlands sydligaste hamn",
    desc: "CE-jobb och lastbilsjobb i Gävle — hamnlogistik, E4/E16 och skogstransport i Gästrikland.",
    transport: "Gävle hamn är en av Sveriges mest aktiva med papper, trä och bulk. E4:an söderut mot Stockholm och E16 västerut mot Dalarna gör Gävle till ett naturligt nav för norrländska godstransporter.",
    highlights: ["Gävle hamn — papper, trä, bulk", "E4 söderut mot Stockholm", "E16 mot Dalarna och Norge", "Skogsindustritransport"],
  },
  {
    slug: "boras",
    name: "Borås",
    region: "Västra Götaland",
    regionSlug: "vastra-gotaland",
    tagline: "E-handelns svenska hem",
    desc: "CE-jobb och lastbilsjobb i Borås — e-handelslogistik, textil och Göteborgsregionens inland.",
    transport: "Borås har historiskt dominerat textilbranschen — och är nu e-handelns logistikcentrum. Stora e-handelsaktörer har sina lager här, med tät distribution mot Göteborg och vidare ut i Sverige.",
    highlights: ["E-handel och returdistribution", "Textillogistik", "Nära Göteborg och E6", "Natt­distribution mot Göteborg"],
  },
  {
    slug: "eskilstuna",
    name: "Eskilstuna",
    region: "Södermanland",
    regionSlug: "sodermanland",
    tagline: "Mälardalens industrihjärta",
    desc: "CE-jobb och lastbilsjobb i Eskilstuna — industritransport, E20 och Södermanlands logistik.",
    transport: "Eskilstuna är en traditionell industristad med stark verkstads­industri. E20 ger direktkoppling mot Stockholm i öst och Göteborg i väst — perfekt för fjärrkörning. Mälaren möjliggör sjötransport av tungt gods.",
    highlights: ["E20 Stockholm–Göteborg", "Verkstadsindustri och specialtransport", "Mälarsjöfart för tunggods", "Distribution i Södermanland"],
  },
  {
    slug: "karlstad",
    name: "Karlstad",
    region: "Värmland",
    regionSlug: "varmland",
    tagline: "Värmlands centrum och E18-navet",
    desc: "CE-jobb och lastbilsjobb i Karlstad — E18 mot Norge, skogsindustri och Värmlands logistik.",
    transport: "Karlstad är Värmlands center och en viktig länk på E18-korridoren mot Norge. Skogsindustrin (papper, kartong) genererar tunga godstransporter. Norge-trafiken ger konstant behov av CE-förare med internationell erfarenhet.",
    highlights: ["E18 mot Oslo och Norge", "Skogsindustri och papperstransport", "Klarälvsdalens råvarutransport", "Internationell Norge-trafik"],
  },
  {
    slug: "vaxjo",
    name: "Växjö",
    region: "Kronoberg",
    regionSlug: "kronoberg",
    tagline: "Smålands logistikstad",
    desc: "CE-jobb och lastbilsjobb i Växjö — IKEA-logistik, E4 och Kronobergs distribution.",
    transport: "Växjö och Kronoberg är starkt präglade av IKEA-sfären och Smålands starka tillverkningsindustri. E4:an passerar genom regionen och skapar ett naturligt flöde av fjärrtransporter söderut mot Malmö och norrut mot Jönköping.",
    highlights: ["IKEA-logistik och möbeltransport", "E4 Malmö–Jönköping", "Småländsk tillverkningsindustri", "Distribution i Kronoberg"],
  },
];

/** Slå upp stad från URL-slug */
export function getCityBySlug(slug) {
  return cityPages.find((c) => c.slug === slug) ?? null;
}
